validation/urls.py
from django.conf.urls import url
from django.contrib import admin
from vapp.views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^pub_form/', pub_form, name='pub_form'),
    url(r'^book_form/', book_form, name='book_form'),
]

vapp/models.py
from django.db import models

class Publisher(models.Model):
    pubname = models.CharField(max_length=20)
    address = models.CharField(max_length=21)
    email = models.EmailField()
    # slug = models.SlugField(max_length=20,null=True)

    def __str__(self):
        return self.pubname

class Book(models.Model):
    title = models.CharField(max_length=21)
    publisher = models.ForeignKey(Publisher)
    pub_date = models.DateField()

    def __str__(self):
        return self.title

vapp/forms.py
from django import forms
from .models import *


class Publisherform(forms.ModelForm):
    def clean_email(self):
        mail = self.cleaned_data['email']

        try:
            match = Publisher.objects.get(email__iexact=mail)
        except:
            return mail
        raise forms.ValidationError("already exists.")

    def clean_pubname(self):
        pname = self.cleaned_data['pubname']

        try:
            match = Publisher.objects.get(pubname__iexact = pname)
        except:
            return pname
        raise forms.ValidationError('already there!!')

    class Meta:
        model = Publisher
        fields = '__all__'


class Bookform(forms.ModelForm):

    #publisher = forms.ModelChoiceField(queryset=Publisher.objects.all())
    #above line is req. if specicfic fields are considered..

    def clean_title(self):
        t = self.cleaned_data['title']

        try:
            book_name = Book.objects.get(title__iexact=t)
        except Book.DoesNotExist:
            return self.cleaned_data['title']
        raise forms.ValidationError("This book already exists.")

    class Meta:
        model = Book
        fields = '__all__'
        # fields='__all__'  #if all field is considered then ModelChoiceField wali line is not req.

class Postform(forms.ModelForm):
    class Meta:
        models = Publisher
        fields = ['title','content']

vapp/views.py
from django.shortcuts import render
from datetime import *
from .models import *
from .forms import *
from django.http import *


def index(request):
    pub = Publisher.objects.all()

    return render(request, 'home.html', {'pub': pub})

def pub_form(request):
    if request.method == 'POST':
        form = Publisherform(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/')

    else:
        form = Publisherform()

    return render(request, 'pub_form.html', {'form':form})

def book_form(request):
    if request.method == 'POST':
        form = Bookform(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/')

    else:
        form = Bookform()

    return render(request, 'book_form.html', {'form': form})

vapp/templates/base.html
<html>
<head>
<title>{% block title %}{% endblock %}</title>
</head>

<body>
{% block content %}
{% endblock %}
</body>

</html>

vapp/templates/book_form.html
{% extends 'base.html' %}

{% block title %}
Basic Django
{% endblock %}

{% block content %}

<h1>Book INFO</h1>

<form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="submit" />

</form>

{% endblock %}

vapp/templates/home.html
{% extends 'base.html' %}

{% block title %}
Basic Django
{% endblock %}

{% block content %}

<h1>HOME PAGE</h1>

<a href="/pub_form/">PUBLICATION FORM</a>
<br>
<a href="/book_form/">BOOK FORM</a>
<br><br>
<div align="center">

    {% for i in pub %}
        <b>Publisher name:{{ i.pubname }}<br>
        Address:{{ i.address }}<br>
            Email:{{ i.email }}<br><br></b>

        {% for j in i.book_set.all %}

        <i> Title: {{ j.title }}<br>
            Publication date: {{ j.pub_date }}<br><br>
        </i>

        {% endfor %}
    <hr width ='500px' />
    {% endfor %}
</div>
<br>

{% endblock %}

vapp/templates/pub_form.html
{% extends 'base.html' %}

{% block title %}
Basic Django
{% endblock %}

{% block content %}

<h1>Publisher INFO</h1>

<form action="" method ="post" >
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="submit" />

</form>

{% endblock %}